<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Talent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TalentSeeder extends Seeder
{
    protected array $data = [
        'Comediantes' => [
            'Los Mascabrothers',
            'Jo Jo Jorge Falcón',
            'Chuponcito',
            'Ale Rivera "La Jarocha"',
            'Jorge Falcón y Nora Velázquez "La Chabelita"',
            'Adrian Uribe',
            'Ariel Miramontes "Albertano"',
            'Javier Carranza "El Costeño"',
            'Edson Zúñiga "El Norteño"',
            'Guerra de Chistes',
            'Radamés de Jesús y La Wanders Lover',
            'Radamés de Jesús',
            'Andrés Bustamante "El Güiri Güiri"',
            'Omar Chaparro',
            'Cessy Casanova',
            'Mago Frank y su Conejo Blas',
            'Pepe Caravelli',
            'Josselyn Borraz',
            'Jaime Rubiel',
            'Archie Balardi',
            'Celedonio',
            'Lalo España',
            'Mara Escalante',
            'Andreas Zanetti',
            'Pavel Arambula',
            'Héctor Ramirez "Rosa Concha"',
            'Michelle Rodríguez',
            'Joe & Moy',
            'Rogelio Ramos',
            'Carlos Eduardo Rico',
            'Gilberto Gless',
            'Teo Gonzalez',
            'El Indio Brayan',
            'Tony Balardi',
            'Óscar Burgos "Perro Guarumo"',
            'Ricardo Hill',
            'Edmundo Miller',
            'Gustavo Munguia',
            'Alma Sureña',
            'Nora Velázquez "Chabelita"',
            'Sergio Corona',
            'Ricardo Margaleff',
            'Payaso Brincos Dieras',
            'Ricardo Fastlicht',
            'El JJ',
            'La India Yuridia',
        ],

        'Standuperos' => [
            'Alan Saldaña',
            'Mike Salazar',
            'Daniel Sosa',
            'Sofía Niño de Rivera',
            'Alex Fernandez',
            'Alexis "Ojitos de Huevo"',
            'Fran Hevia',
            'Alexis de Anda',
        ],

        'Youtuberos' => [
            'Luisito Comunica',
            'Berth Oh',
            'Gomita',
            'Lapizito',
            'Juanpa Zurita',
            'Juca',
            'Mario Bautista',
            'Yuya',
            'Los Polinesios',
            'Werevertumorro',
            'El Escorpión Dorado',
        ],

        'Conductores' => [
            'Cecilia Galliano',
            'Andrea Legarreta',
            'Andrea Escalona Rodríguez',
            'Galilea Montijo',
            'Luz María Zetina',
            '"El Burro" Van Rankin',
            'Juan José "Pepillo" Origel',
            'Raul Araiza',
            'Carlos Arenas',
            'Adal Ramones',
            'Verónica Macias',
            'Yordi Rosado',
            'Facundo',
            'Mónica Garza',
            'Paulina Mercado',
            'Mauricio Barcelata',
            'Martha Debayle',
            'El Capi Pérez',
            'Natalia Tellez',
            'Marco Antonio Regil',
            'Faisy',
        ],

        'Artistas Musicales y Atractivo Visual' => [
            'Dorismar',
            'Ninel Conde',
            'Maribel Guardia',
            'Ivonnne Montero',
            'Aleida Nuñez',
            'Paola Durante',
            'Niurka Marcos',
            'Paty Muñoz',
            'Marlene Fabela',
            'Liz Vega',
            'Laura León',
            'Wanders Lover',
            'Lorena Herrera',
        ],

        'Grupos y Bandas Musicales' => [
            'Sonora Dinamita',
            'Los Ángeles Azules',
            'Grupo Cañaveral',
            'Rayito Colombiano',
            'Campeche Show con Ray',
            'Aaron y su Grupo Ilusión',
            'Los Yaguaru',
            'Aroma',
            'Los Socios del Ritmo',
            'Sonora Santanera de Carlos Colorado y Maria Fernanda',
            'La Sonora de Margarita',
            'El Super Show de los Vazkez',
            'Grupo Brindis',
            'Los Angeles de Charly',
            'Junior Klan',
            'Los Llayras',
            'Bronco',
            'Caballo Dorado',
            'Alberto Barros',
            'Los Chinacos de Toño Medina',
            'Los Acosta',
        ],

        'Banda' => [
            'Banda Cuisillos',
            'Banda La Ejecutiva de Mazatlan',
            'Banda MS',
            'Marca MP',
            'Banda Los Sebastianes',
            'Banda Todo Terreno',
            'Banda Los Recoditos',
            'Grupo Frontera',
            'Grupo El Duelo',
            'Grupo Legitimo',
            'Eden Muñoz',
            'Los Ávila',
            'Lupillo Rivera',
            'Banda El Mexicano de Casimiro',
            'Edwin Luna y La Trakalosa de Monterrey',
            'La Adictiva',
            'La Arrolladora Banda El Limón',
            'Chuy Lizarraga',
            'Los Valedores de la Sierra',
            'Grupo Firme',
            'Banda Tierra Sagrada',
            'La Septima Banda',
            'Intocable',
            'Ana Barbara',
            'Kumbia Kings',
            'Bobby Pulido',
            'Los Primos',
            '3BallMTY',
            'Griss Romero',
            'Montéz de Durango',
            'Patrulla81',
            'El Yaki',
            'El Bebeto',
            'Carlos Sarabia',
            'Saúl "El Jaguar"',
            'Banda Pequeños Musical',
            'Rigo Tovar Jr.',
            'Banda Machos',
            'Autentica Sonora Santanera de Gildardo Zarate',
            'Cardenales de Nuevo León',
            'Julio Preciado',
            'Liberación',
            'Los Cadetes de Linares',
            'Banda El Recodo',
            'Los Trigres del Norte',
        ],

        'Trios románticos' => [
            'Trio Los Panchos',
            'Trio Los Tecolines',
            "Trio Los Dandy's",
            'Los Tres Ases',
        ],

        'Mariachis' => [
            'Mariachi Gama Mil',
            'Mariachi Vargas de Tecalitlán',
            'Mariachi México de Pepe Villa',
            'Mariachi Internacional Guadalajara',
        ],

        'Música Pop, Romántica, Rock y Urbana' => [
            'Jesse y Joy',
            'Cristian Castro',
            'Emmanuel',
            'Emmanuel & Mijares',
            'Manuel Mijares',
            'Jaime Varela "Tributo a Juan Gabriel"',
            'Gloria Trevi',
            'Paulina Rubio',
            'Alejandra Guzman',
            'Belinda',
            'Ximena Sariñana',
            'Edith Márquez',
            'Paty Cantú',
            'María José',
            'Daniela Romo',
            'Reik',
            'Yuri',
            'María León',
            'Erik y Mia Rubín',
            'Pandora',
            'Pandora & Flans',
            'Carlos Rivera',
            'Coque Muñiz',
            'Nicho Hinojosa',
            'Carlos Cuevas',
            'Los Teen Tops',
            'Victor García',
            'El Tri',
            'Molotov',
            'Moenia',
            'Mau y Ricky Montaner',
            'Ricardo Montaner',
            'Aleks Syntek',
            'Rio Roma',
            'Yuridia',
            'Zoé',
            'Sasha Sokol',
            'Ana Torroja',
            'Fobia',
            'Karol Sevilla',
            'Benny Ibarra',
            'Erik Rubin',
            'Horacio Palencia',
            'Ha*Ash',
            'Kinky',
            'Morat',
            'Motel',
            'Sebastián Yatra',
            'Yahir',
            'Caifanes',
            'David Bisbal',
            'Juanes',
            'Lucero',
            'Farruko',
            'Bad Bunny',
            'Sin Bandera',
            'Camila',
            'Manuel Turizo',
            'Nicky Jam',
            'Romeo Santos',
            'Matute',
            'Matisse',
            'Maluma',
            'Camilo',
            'Déjá Vu',
            'Trendline',
            'Kapsula',
            'Mixon',
            'Factor Cumbia',
        ],

        'Conferencistas' => [
            'Helios Herrera',
            'Carlos Loret de Mola',
            'Cesar Lozano',
            'Odin Dupeyron',
            'Victor Trujillo "Brozo"',
            'Sergio Sarmiento',
            'Lorena Ochoa',
            'Felipe Calderón',
            'Ernesto Zedillo',
            'Enrique Krauze',
            'Diego Luna',
        ],

        'Actores y Actrices' => [
            'Julian Gil',
            'Andrés Palacios',
            'Raul Magaña',
            'Eugenio Derbez',
            'Arturo Peniche',
            'Eduardo Yañez',
            'Sebastián Rulli',
            'José Ron',
            'Fernando Colunga',
            'Gabriel Soto',
            'Demián Bichir',
            'Vadhir Derbez',
            'Eduardo Capetillo',
            'William Levy',
            'Jaime Camil',
            'Mauricio Ochmann',
            'Diego Boneta',
            'Jorge Salinas',
            'Eduardo Santamarina',
            'Mark Tacher',
            'Julio Camejo',
            'Luis Roberto Guzmán',
            'Maite Perroni',
            'Laura Zapata',
            'Aislinn Derbez',
            'Erika Buenfil',
            'Ludwika Paleta',
            'Angelique Boyer',
            'Chantal Andere',
            'Victoria Ruffo',
            'Itatí Cantoral',
        ],

        'Regional Mexicano y Ranchero' => [
            'Christian Nodal',
            'Alejandro Fernández',
            'Pepe Aguilar',
            'Pedro Fernández',
            'Pablo Montero',
            'Espinoza Paz',
            'Carin León',
            'Los Dos Carnales',
            'Alexander García "El Fantasma"',
            'Natanael Cano',
            'Ángela Aguilar',
            'Junior H',
            'Alfredo Olivas',
            'Gerardo Ortiz',
            'Luis Antonio "El Mimoso"',
            'Jorge Medina',
            'Julion Alvarez',
            'Raul Sandoval',
        ],
    ];

    public function run(): void
    {
        foreach ($this->data as $categoryName => $talents) {
            $category = Category::where('slug', Str::slug($categoryName))->first();

            if (! $category) {
                $this->command->warn("Categoría no encontrada: {$categoryName}");
                continue;
            }

            foreach ($talents as $name) {
                $talent = Talent::firstOrCreate(
                    ['slug' => 'contrataciones-' . Str::slug($name)],
                    ['name' => $name, 'is_active' => true]
                );

                $talent->categories()->syncWithoutDetaching([$category->id]);
            }
        }
    }
}