<?php

return [
    'Aguascalientes' => 'MXAGU',
    'Baja California' => 'MXBCN',
    'Baja California Sur' => 'MXBCS',
    'Campeche' => 'MXCAM',
    'Chiapas' => 'MXCHP',
    'Chihuahua' => 'MXCHH',
    'Ciudad de México' => 'MXCMX',
    'Coahuila' => 'MXCOA',
    'Colima' => 'MXCOL',
    'Durango' => 'MXDUR',
    'Estado de México' => 'MXMEX',
    'Guanajuato' => 'MXGUA',
    'Guerrero' => 'MXGRO',
    'Hidalgo' => 'MXHID',
    'Jalisco' => 'MXJAL',
    'Michoacán' => 'MXMIC',
    'Morelos' => 'MXMOR',
    'Nayarit' => 'MXNAY',
    'Nuevo León' => 'MXNLE',
    'Oaxaca' => 'MXOAX',
    'Puebla' => 'MXPUE',
    'Querétaro' => 'MXQUE',
    'Quintana Roo' => 'MXROO',
    'San Luis Potosí' => 'MXSLP',
    'Sinaloa' => 'MXSIN',
    'Sonora' => 'MXSON',
    'Tabasco' => 'MXTAB',
    'Tamaulipas' => 'MXTAM',
    'Tlaxcala' => 'MXTLA',
    'Veracruz' => 'MXVER',
    'Yucatán' => 'MXYUC',
    'Zacatecas' => 'MXZAC',
];